### ISSUE TITLE
Installer immediately fails after confirmation

### ISSUE THREAD

**Issue by bi0shacker001** [Vanilla-OS/vanilla-installer#305]
I can get through the entire process of configuring the installation, but a split second after I confirm it, the carousel launches, then I get thid error message:
![291be6d5-4e06-4ad5-b3ff-51204fcc4096](https://github.com/Vanilla-OS/vanilla-installer/assets/6968622/4eba7e5f-e8c4-4934-b6ae-389111a956c1)
There are no other logs, that's the entirety of the message. And it happens on every version of the installer.

The system works fine on other linux distros, boots the installer fine, but this error occurs on every version of the iso that was downloadable as of 11 est this morning.

**Comment by kbdharun** [comment]
Hi, I was discussing the same issue with @matbme yesterday (when testing the latest build). Can you try rerunning the installer by typing `vanilla-installer` in the Console? The installation would probably complete this time.

**Comment by bi0shacker001** [comment]
I'm uncertain how to get a terminal window in the limited session the
installer launches, but logging out to force an immediate log back in and
relaunch the installer doesn't correct the issue.
Should I be seeing a full gnome session for the installer? Because I have
never had a full session

**Comment by kbdharun** [comment]
You can open Settings from the Quick Settings panel in the top right corner in the Keyboard panel to create a new custom shortcut for the terminal [the command is `kgx`]. Then execute the shortcut key combination once which will open the terminal. Then you can type `vanilla-installer` to run it again.

**Comment by matbme** [comment]
Is would also be useful to know the output of `lsblk` after the command fails.

**Comment by thomas-shirley** [comment]
Hi All — I can replicate this bug:

from terminal output:
```vanilla@vanillaos:~$ vanilla-installer
INFO:Installer::Builder:Performing display-condition: lspci | grep -i '.* nvidia .*'
INFO:Installer::Builder:Step nvidia skipped due to display-conditions
INFO:Installer::Processor:processing the following final data: [{}, {'language': 'en_GB.UTF-8'}, {'keyboard': {'layout': 'gb', 'model': 'pc105', 'variant': 'mac_intl'}}, {}, {}, {'timezone': {'region': 'Europe', 'zone': 'London'}}, {'disk': {'auto': {'disk': '/dev/nvme0n1', 'pretty_size': '233.76 GB', 'size': 251000193024}}}, {'encryption': {'use_encryption': True, 'encryption_key': 'test'}}]

(vanilla-installer:6744): VTE-WARNING **: 16:41:11.455: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)

(vanilla-installer:6744): Adwaita-CRITICAL **: 16:43:41.950: adw_carousel_get_nth_page: assertion 'n < adw_carousel_get_n_pages (self)' failed
Traceback (most recent call last):
  File "/usr/share/org.vanillaos.Installer/vanilla_installer/defaults/conn_check.py", line 97, in callback
    self.__window.next()
  File "/usr/share/org.vanillaos.Installer/vanilla_installer/windows/main_window.py", line 119, in next
    self.carousel.scroll_to(page, True)
TypeError: Argument 1 does not allow None as a value

from installer pop-up log:

Setup [1/20]: label
panic: failed to run setup operation label: failed to label disk: Error: Partition(s) 3, 4 on /dev/nvme0n1 have been w ritten, but we have been unable to inform the kernel of the change, probably because it/they are in use. As a result, the old partition(s) will remain in use. You should reboo t now before making further changes.
goroutine 1 [running]: main.main()
github.com/vanilla-os/albius/albius.go:22 +0×106

**Comment by M15071060** [comment]
Apologies if this isn't helpful, but this same message appeared on an install just now, though installing on a virtual machine wherein I had initially created it with UEFI. Recreating the VM with `UEFI x86_64: /usr/share/OVMF/OVMF_CODE_4M.secboot.fd` set as the firmware enabled the creation and installation of VanillaOS

 Running Debian GNU/Linux 12 (bookworm) x86_64, Kernel 6.1.0-30-amd64
