### ISSUE TITLE
Typo for the NVIDIA Proprietary Image left in

### ISSUE THREAD

**Issue by Cjnator38** [Vanilla-OS/vanilla-installer#415]
I was attempting to install Orchid a second time and I got stuck on the "Confirm Installation" screen. Turns out the installer is still trying to pull the "nvidia-propietary" image instead of the "nvidia-proprietary" image

**Comment by mirkobrombin** [comment]
Are you using latest ISO? Started a new one to be sure since the fix is already there

**Comment by Cjnator38** [comment]
```INFO:Installer::Processor:processing the following final data: [{}, {'language': 'en_US.UTF-8'}, {'keyboard': [{'layout': 'us', 'model': 'pc105', 'variant': ''}]}, {}, {}, {'timezone': {'region': 'America', 'zone': 'Chicago'}}, {'nvidia': {'use-proprietary': True, 'use-open': False}}, {'default-image': True}, {'disk': {'auto': {'disk': '/dev/sda', 'pretty_size': '238.47 GB', 'size': 256060514304, 'vgs_to_remove': ['vos-root', 'vos-var'], 'pvs_to_remove': ['/dev/sda3', '/dev/sda4']}}}, {'encryption': {'use_encryption': False, 'encryption_key': ''}}]
Traceback (most recent call last):
  File "/usr/share/org.vanillaos.Installer/vanilla_installer/windows/main_window.py", line 136, in on_installation_confirmed
    recipe = Processor.gen_install_recipe(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/org.vanillaos.Installer/vanilla_installer/utils/processor.py", line 490, in gen_install_recipe
    oci_image = images["nvidia-propietary"]
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'nvidia-propietary'

This is what shows up when I click the install button. Seems like the typo was left in one of the Python scripts used by the installer. Installing by clicking "Install Custom Image (Advanced)" bypasses this error (although I'm getting the "can't initialize physical volume" error again).

**Comment by mirkobrombin** [comment]
fixed and started a new build, ty
